# Generated by Django 3.1.6 on 2021-02-05 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_auto_20210204_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='descricao_slug',
            new_name='slug',
        ),
    ]
