# Generated by Django 3.1.6 on 2021-02-04 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.IntegerField()),
                ('data_nascimento', models.DateTimeField()),
                ('cpf', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=255)),
                ('complemento', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=150)),
                ('cep', models.CharField(max_length=8)),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('SP', 'São Paulo')], default='SP', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
