# Generated by Django 2.2.12 on 2021-02-08 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_perfiluser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilUser',
        ),
    ]
