# Generated by Django 3.1.7 on 2021-03-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_pedido_qtd_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='preco',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
